// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(lv_obj_t * parent);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Calendar1;
lv_obj_t *ui_Image1;
lv_obj_t *ui____initial_actions0;


void ui_Music_page_init(lv_obj_t * parent);
lv_obj_t *ui_Screen;
lv_obj_t *ui_Panel;
lv_obj_t *ui_Panele;
void ui_event_PausBtn( lv_event_t * e);
lv_obj_t *ui_PausBtn;
void ui_event_PreBtn( lv_event_t * e);
lv_obj_t *ui_PreBtn;
void ui_event_NextBtn( lv_event_t * e);
lv_obj_t *ui_NextBtn;
lv_obj_t *ui_Playback_progressSlider;
lv_obj_t *ui_CurTimeLabel1;
lv_obj_t *ui_AllTimeLabel;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_SongWrite;
lv_obj_t *ui_SongTitle;
void ui_event_ModeLabel( lv_event_t * e);
lv_obj_t *ui_ModeLabel;
lv_obj_t *ui_PlayList;
void ui_event_VoiceButton( lv_event_t * e);
void ui_event_VolumeSlider( lv_event_t * e);
lv_obj_t *ui_VoiceButton;
lv_obj_t *ui_VolumeSlider;
lv_obj_t *ui____initial_actions0;
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
//ui_Screen1_screen_init();
//ui____initial_actions0 = lv_obj_create(NULL);
//lv_disp_load_scr( ui_Screen1);
}
