// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(lv_obj_t * parent);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Calendar1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui____initial_actions0;

void ui_Music_page_init(lv_obj_t * parent);
extern lv_obj_t *ui_Screen;
extern lv_obj_t *ui_Panel;
extern lv_obj_t *ui_Panele;
void ui_event_PausBtn( lv_event_t * e);
extern lv_obj_t *ui_PausBtn;
void ui_event_PreBtn( lv_event_t * e);
extern lv_obj_t *ui_PreBtn;
void ui_event_NextBtn( lv_event_t * e);
extern lv_obj_t *ui_NextBtn;
extern lv_obj_t *ui_Playback_progressSlider;
extern lv_obj_t *ui_CurTimeLabel1;
extern lv_obj_t *ui_AllTimeLabel;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_SongWrite;
extern lv_obj_t *ui_SongTitle;
void ui_event_ModeLabel( lv_event_t * e);
extern lv_obj_t *ui_ModeLabel;
extern lv_obj_t *ui_PlayList;
void ui_event_VoiceButton( lv_event_t * e);
void ui_event_VolumeSlider( lv_event_t * e);
extern lv_obj_t *ui_VoiceButton;
extern lv_obj_t *ui_VolumeSlider;
//extern lv_obj_t *ui____initial_actions0;

//LV_IMG_DECLARE( ui_img_698092854);   // assets\听歌学习.png
LV_IMG_DECLARE( ui_img_930994846)
LV_IMG_DECLARE( ui_img_264944503);   // assets\播放.png
LV_IMG_DECLARE( ui_img_865762230);   // assets\上一首.png
LV_IMG_DECLARE( ui_img_850639887);   // assets\下一首.png
LV_IMG_DECLARE( ui_img_655471181);   // assets\列表.png
LV_IMG_DECLARE( ui_img_1088127317);   // assets\声音.png
LV_IMG_DECLARE( ui_img_weather_png);   // assets\weather.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
