// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "OSTask.h"
void ui_Music_page_init(lv_obj_t * parent)
{
ui_Screen =parent;
lv_obj_clear_flag( ui_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel = lv_obj_create(ui_Screen);
lv_obj_set_width( ui_Panel, 480);
lv_obj_set_height( ui_Panel, 800);
lv_obj_set_x( ui_Panel, -2 );
lv_obj_set_y( ui_Panel, -4 );
lv_obj_set_align( ui_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel, lv_color_hex(0x495560), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel, lv_color_hex(0x495560), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_Panele = lv_img_create(ui_Panel);
lv_obj_set_width( ui_Panele, 200);
lv_obj_set_height( ui_Panele, 200);
lv_obj_set_x( ui_Panele, 0 );
lv_obj_set_y( ui_Panele, -220 );
lv_obj_set_align( ui_Panele, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panele, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
//lv_img_set_src( ui_Panele, "0:/image/Learn.png");

ui_PausBtn = lv_obj_create(ui_Panel);
lv_obj_set_width( ui_PausBtn, 80);
lv_obj_set_height( ui_PausBtn, 80);
lv_obj_set_x( ui_PausBtn, 0 );
lv_obj_set_y( ui_PausBtn, -70 );
lv_obj_set_align( ui_PausBtn, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PausBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PausBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PausBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PausBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PausBtn, &ui_img_264944503, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_PausBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PausBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PausBtn, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PreBtn = lv_obj_create(ui_Panel);
lv_obj_set_width( ui_PreBtn, 60);
lv_obj_set_height( ui_PreBtn, 60);
lv_obj_set_x( ui_PreBtn, 80 );
lv_obj_set_y( ui_PreBtn, -81 );
lv_obj_set_align( ui_PreBtn, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_state( ui_PreBtn, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_PreBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PreBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PreBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PreBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PreBtn, &ui_img_865762230, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_PreBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PreBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NextBtn = lv_obj_create(ui_Panel);
lv_obj_set_width( ui_NextBtn, 60);
lv_obj_set_height( ui_NextBtn, 60);
lv_obj_set_x( ui_NextBtn, -80 );
lv_obj_set_y( ui_NextBtn, -81 );
lv_obj_set_align( ui_NextBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_NextBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NextBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NextBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NextBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_NextBtn, &ui_img_850639887, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_NextBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NextBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Playback_progressSlider = lv_slider_create(ui_Panel);
lv_obj_set_width( ui_Playback_progressSlider, 390);
lv_obj_set_height( ui_Playback_progressSlider, 9);
lv_obj_set_x( ui_Playback_progressSlider, 0 );
lv_obj_set_y( ui_Playback_progressSlider, 152 );
lv_obj_set_align( ui_Playback_progressSlider, LV_ALIGN_CENTER );
//    lv_obj_clear_flag(ui_Playback_progressSlider,LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_style_bg_color(ui_Playback_progressSlider, lv_color_hex(0x46403D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Playback_progressSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Playback_progressSlider, lv_color_hex(0xFFE229), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Playback_progressSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Playback_progressSlider, lv_color_hex(0xFFE229), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Playback_progressSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_CurTimeLabel1 = lv_label_create(ui_Panel);
lv_obj_set_width( ui_CurTimeLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CurTimeLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CurTimeLabel1, -194 );
lv_obj_set_y( ui_CurTimeLabel1, 192 );
lv_obj_set_align( ui_CurTimeLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_CurTimeLabel1,"0:0");
lv_obj_set_style_text_font(ui_CurTimeLabel1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AllTimeLabel = lv_label_create(ui_Panel);
lv_obj_set_width( ui_AllTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AllTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AllTimeLabel, 191 );
lv_obj_set_y( ui_AllTimeLabel, 189 );
lv_obj_set_align( ui_AllTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AllTimeLabel,"0:0");
lv_obj_set_style_text_font(ui_AllTimeLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel);
lv_obj_set_width( ui_Label3, 88);
lv_obj_set_height( ui_Label3, 26);
lv_obj_set_x( ui_Label3, -112 );
lv_obj_set_y( ui_Label3, 2 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Song title\n");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Panel);
lv_obj_set_width( ui_Label4, 107);
lv_obj_set_height( ui_Label4, 23);
lv_obj_set_x( ui_Label4, -106 );
lv_obj_set_y( ui_Label4, 49 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Song writer");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SongWrite = lv_label_create(ui_Panel);
lv_obj_set_width( ui_SongWrite, 96);
lv_obj_set_height( ui_SongWrite, 23);
lv_obj_set_x( ui_SongWrite, 84 );
lv_obj_set_y( ui_SongWrite, 43 );
lv_obj_set_align( ui_SongWrite, LV_ALIGN_CENTER );
lv_label_set_text(ui_SongWrite,"NULL");

ui_SongTitle = lv_label_create(ui_Panel);
lv_obj_set_width( ui_SongTitle, 96);
lv_obj_set_height( ui_SongTitle, 23);
lv_obj_set_x( ui_SongTitle, 83 );
lv_obj_set_y( ui_SongTitle, -4 );
lv_obj_set_align( ui_SongTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SongTitle,"NULL\n");

ui_ModeLabel = lv_label_create(ui_Panel);
lv_obj_set_width( ui_ModeLabel, 102);
lv_obj_set_height( ui_ModeLabel, 43);
lv_obj_set_x( ui_ModeLabel, 0 );
lv_obj_set_y( ui_ModeLabel, -75 );
lv_obj_set_align( ui_ModeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ModeLabel,"Sequential playback\n");
lv_obj_set_style_text_align(ui_ModeLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ModeLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PlayList = lv_imgbtn_create(ui_Panel);
lv_imgbtn_set_src(ui_PlayList, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_655471181, NULL);
lv_obj_set_width( ui_PlayList, 40);
lv_obj_set_height( ui_PlayList, 40);
lv_obj_set_x( ui_PlayList, -150 );
lv_obj_set_y( ui_PlayList, -75 );
lv_obj_set_align( ui_PlayList, LV_ALIGN_CENTER );

ui_VoiceButton = lv_imgbtn_create(ui_Panel);
lv_imgbtn_set_src(ui_VoiceButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1088127317, NULL);
lv_obj_set_width( ui_VoiceButton, 40);
lv_obj_set_height( ui_VoiceButton, 40);
lv_obj_set_x( ui_VoiceButton, 150 );
lv_obj_set_y( ui_VoiceButton, -75 );
lv_obj_set_align( ui_VoiceButton, LV_ALIGN_CENTER );

ui_VolumeSlider = lv_slider_create(ui_Panel);
lv_obj_set_width( ui_VolumeSlider, 9);
lv_obj_set_height( ui_VolumeSlider, 143);
lv_obj_set_x( ui_VolumeSlider, 147 );
lv_obj_set_y( ui_VolumeSlider, -192 );
lv_slider_set_range(ui_VolumeSlider,0,63);
lv_obj_set_align( ui_VolumeSlider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_VolumeSlider, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_VolumeSlider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0x46403D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xFFE229), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xFFE229), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PausBtn, ui_event_PausBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PreBtn, ui_event_PreBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NextBtn, ui_event_NextBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ModeLabel, ui_event_ModeLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VoiceButton, ui_event_VoiceButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VolumeSlider, ui_event_VolumeSlider, LV_EVENT_ALL, NULL);

}
