// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(lv_obj_t * parent)
{
ui_Screen1 = (parent);
//lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(parent);
lv_obj_set_width( ui_Panel1, 770);
lv_obj_set_height( ui_Panel1, 450);
lv_obj_set_x( ui_Panel1, 5 );
lv_obj_set_y( ui_Panel1, 5 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x47308C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Panel2 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel2, 497);
lv_obj_set_height( ui_Panel2, 257);
lv_obj_set_x( ui_Panel2, -125 );
lv_obj_set_y( ui_Panel2, 89 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x26212F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 263 );
lv_obj_set_y( ui_Label1, -189 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Ttime\n_______________________");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 178 );
lv_obj_set_y( ui_Label2, -141 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Hour:");

ui_Label3 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 185 );
lv_obj_set_y( ui_Label3, -97 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Minute:");

ui_Label4 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 248 );
lv_obj_set_y( ui_Label4, -140 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );

ui_Label5 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 253 );
lv_obj_set_y( ui_Label5, -95 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );

ui_Label6 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -149 );
lv_obj_set_y( ui_Label6, -153 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"May the world be more gentle and may you be less sad.");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -95 );
lv_obj_set_y( ui_Label7, -135 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"__________________________________________");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -228 );
lv_obj_set_y( ui_Label8, -81 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Weather:");

ui_Label9 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -167 );
lv_obj_set_y( ui_Label9, -80 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );

ui_Calendar1 = lv_calendar_create(ui_Screen1);
lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
lv_obj_set_width( ui_Calendar1, 230);
lv_obj_set_height( ui_Calendar1, 240);
lv_obj_set_x( ui_Calendar1, 264 );
lv_obj_set_y( ui_Calendar1, 81 );
lv_obj_set_align( ui_Calendar1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Calendar1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_weather_png);
lv_obj_set_width( ui_Image1, 64);
lv_obj_set_height( ui_Image1, 64);
lv_obj_set_x( ui_Image1, -306 );
lv_obj_set_y( ui_Image1, -88 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Image1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0x404744), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);


}
